name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AIAOP_HOST }}
          username: ${{ secrets.AIAOP_USER }}
          password: ${{ secrets.AIAOP_PASSWORD }}
          port: 22
          script: |
            # Ensure npm and node are in the PATH
            export PATH=$PATH:/home/${{ secrets.AIAOP_USER }}/.nvm/versions/node/v22.17.1/bin

            # Check if npm is available
            which npm || { echo "npm not found"; exit 1; }

            echo "Starting deployment process..."

            # Navigate to the application's directory
            cd /home/abracodebra-aop-photobooth/htdocs/aop-photobooth.abracodebra.com/photobooth-cloud-aop || exit

            # Pull the latest changes from the GitHub repository
            git pull origin main

            # Install dependencies
            npm install

            # Reload or restart the application using PM2
            pm2 reload ecosystem.config.js --env production

            # Save the PM2 process list and startup script
            pm2 save

            # Set up PM2 to start on boot with systemd
            pm2 startup systemd -u ${USER} --hp /home/${USER}

            # Exit with a success message
            echo "Deployment complete!"
            exit 0